name: trialmatch
version: 1.0.0
config-version: 2
profile: trialmatch

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: target
clean-targets: [target, dbt_packages]

models:
  trialmatch:
    staging:
      +schema: STAGING
      +materialized: view
    marts:
      +schema: MARTS
      +materialized: table
    audit:
      +schema: AUDIT
      +materialized: view
      +enabled: true
