apiVersion: v1
kind: Service
metadata:
  name: trialmatch-api
  namespace: trialmatch
  labels:
    app.kubernetes.io/name: trialmatch-api
  annotations:
    cloud.google.com/backend-config: '{"default":"trialmatch-api-backend-config"}'
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: trialmatch-api
  ports:
    - name: http
      port: 80
      targetPort: http
