-- Phase 5: Warehouse, database, and RBAC roles (no schema grants yet — see 03_*).
-- Run as ACCOUNTADMIN / SECURITYADMIN before 03_schemas_tables.sql.

CREATE WAREHOUSE IF NOT EXISTS TRIALMATCH_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'trialmatch agent warehouse';

CREATE DATABASE IF NOT EXISTS TRIALMATCH_DEV
  COMMENT = 'Autonomous clinical trial matching (dev)';

CREATE ROLE IF NOT EXISTS AGENT_READ_ROLE
  COMMENT = 'Matcher / analytics read access to marts';

CREATE ROLE IF NOT EXISTS AUDIT_WRITE_ROLE
  COMMENT = 'Auditor append access to audit tables';

GRANT USAGE ON WAREHOUSE TRIALMATCH_WH TO ROLE AGENT_READ_ROLE;
GRANT USAGE ON WAREHOUSE TRIALMATCH_WH TO ROLE AUDIT_WRITE_ROLE;

GRANT USAGE ON DATABASE TRIALMATCH_DEV TO ROLE AGENT_READ_ROLE;
GRANT USAGE ON DATABASE TRIALMATCH_DEV TO ROLE AUDIT_WRITE_ROLE;

-- Application user (keypair auth; private key in Secret Manager — never in git)
-- CREATE USER IF NOT EXISTS TRIALMATCH_APP ... RSA_PUBLIC_KEY='...' ;
-- GRANT ROLE AGENT_READ_ROLE TO USER TRIALMATCH_APP;
-- GRANT ROLE AUDIT_WRITE_ROLE TO USER TRIALMATCH_APP;
