-- Phase 5: Schemas + Synthea-aligned landing tables + audit table + RBAC grants.
-- Seed script writes to RAW_SYNTHEA_* via scripts/seed_snowflake_from_synthea.py
-- Prerequisite: 01_roles.sql (warehouse + database + roles).

USE DATABASE TRIALMATCH_DEV;

CREATE SCHEMA IF NOT EXISTS RAW COMMENT = 'Synthea / upstream landing';
CREATE SCHEMA IF NOT EXISTS STAGING COMMENT = 'dbt staging models';
CREATE SCHEMA IF NOT EXISTS MARTS COMMENT = 'dbt marts for Matcher';
CREATE SCHEMA IF NOT EXISTS AUDIT COMMENT = 'Auditor justifications / append-only logs';

CREATE TABLE IF NOT EXISTS RAW.RAW_SYNTHEA_PATIENTS (
  ID VARCHAR,
  BIRTHDATE DATE,
  GENDER VARCHAR,
  RACE VARCHAR,
  ETHNICITY VARCHAR,
  CITY VARCHAR,
  STATE VARCHAR,
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.RAW_SYNTHEA_LABS (
  PATIENT VARCHAR,
  DATE TIMESTAMP_NTZ,
  CODE VARCHAR,
  DESCRIPTION VARCHAR,
  VALUE FLOAT,
  UNITS VARCHAR,
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.RAW_SYNTHEA_CONDITIONS (
  PATIENT VARCHAR,
  START DATE,
  STOP DATE,
  CODE VARCHAR,
  DESCRIPTION VARCHAR,
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.RAW_SYNTHEA_ENCOUNTERS (
  ID VARCHAR,
  PATIENT VARCHAR,
  START TIMESTAMP_NTZ,
  STOP TIMESTAMP_NTZ,
  ENCOUNTERCLASS VARCHAR,
  CODE VARCHAR,
  DESCRIPTION VARCHAR,
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS AUDIT.AUDIT_MATCH_JUSTIFICATIONS (
  MATCH_ID VARCHAR NOT NULL,
  PATIENT_ID VARCHAR NOT NULL,
  NCT_ID VARCHAR,
  JUSTIFICATION VARCHAR NOT NULL,
  AGENT_NAME VARCHAR DEFAULT 'auditor',
  CORRELATION_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Schema USAGE
GRANT USAGE ON SCHEMA TRIALMATCH_DEV.RAW TO ROLE AGENT_READ_ROLE;
GRANT USAGE ON SCHEMA TRIALMATCH_DEV.STAGING TO ROLE AGENT_READ_ROLE;
GRANT USAGE ON SCHEMA TRIALMATCH_DEV.MARTS TO ROLE AGENT_READ_ROLE;
GRANT USAGE ON SCHEMA TRIALMATCH_DEV.AUDIT TO ROLE AGENT_READ_ROLE;
GRANT USAGE ON SCHEMA TRIALMATCH_DEV.AUDIT TO ROLE AUDIT_WRITE_ROLE;

-- Matcher: SELECT on marts / staging / raw
GRANT SELECT ON ALL TABLES IN SCHEMA TRIALMATCH_DEV.MARTS TO ROLE AGENT_READ_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TRIALMATCH_DEV.MARTS TO ROLE AGENT_READ_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA TRIALMATCH_DEV.STAGING TO ROLE AGENT_READ_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TRIALMATCH_DEV.STAGING TO ROLE AGENT_READ_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA TRIALMATCH_DEV.RAW TO ROLE AGENT_READ_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TRIALMATCH_DEV.RAW TO ROLE AGENT_READ_ROLE;

-- Auditor: INSERT (+ SELECT own rows) on audit — not write access to clinical landing
GRANT INSERT ON ALL TABLES IN SCHEMA TRIALMATCH_DEV.AUDIT TO ROLE AUDIT_WRITE_ROLE;
GRANT INSERT ON FUTURE TABLES IN SCHEMA TRIALMATCH_DEV.AUDIT TO ROLE AUDIT_WRITE_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA TRIALMATCH_DEV.AUDIT TO ROLE AUDIT_WRITE_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TRIALMATCH_DEV.AUDIT TO ROLE AUDIT_WRITE_ROLE;

-- dbt runner typically needs CREATE on STAGING/MARTS (use a dedicated transform role in prod)
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA TRIALMATCH_DEV.STAGING TO ROLE AGENT_READ_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA TRIALMATCH_DEV.MARTS TO ROLE AGENT_READ_ROLE;
